[package]
name = "API-CALL"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = {version="0.12.9" , features = ["blocking" ,"json"]}
serde_json="1.0.132"
serde = {version="1.0.132", features=["derive"]}
tokio = {version="1.21.2", features=["full"]}
