[package]
name = "async-await"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest={version ="0.12.9", features = ["blocking","json"]}
tokio= {version = "1.41.0",features = ["full"]}
error-chain="0.12.4"